from __future__ import annotations

from pathlib import Path

from analysis.physics import characteristic_length, drag_coefficient, reynolds_number
from analysis.regimes import FlowRegime
from analysis.scorecard import DesignScorecard
from analysis.sanity import SanityWarning
from engines.base import SimEngine
from scene.scene import Scene


def export_markdown_report(
    path: str | Path,
    scene: Scene,
    sim: SimEngine,
    step_count: int,
    regime: FlowRegime | None = None,
    warnings: list[SanityWarning] | None = None,
    scorecard: DesignScorecard | None = None,
) -> None:
    warnings = warnings or []
    length = characteristic_length(scene)
    re = reynolds_number(sim, length)
    cd = drag_coefficient(sim)
    lines = [
        f"# {scene.name} Flow Report",
        "",
        scene.product.export_caption or scene.description or "SStream fluid snapshot.",
        "",
        "## Key Readouts",
        "",
        f"- Step: {step_count}",
        f"- Reynolds number: {re:.1f}",
        f"- Drag coefficient estimate: {cd:.3f}",
        f"- Characteristic length: {length:.1f} lattice cells",
        f"- Inflow velocity: {sim.u_inflow}",
        f"- Viscosity: {sim.viscosity}",
        "",
        "## Flow Regime",
        "",
        regime.explanation if regime else "No regime estimate available yet.",
    ]
    if regime:
        lines.extend([
            "",
            f"- Label: {regime.label}",
            f"- Confidence: {regime.confidence:.0%}",
            (
                f"- Strouhal estimate: {regime.strouhal:.3f}"
                if regime.strouhal
                else "- Strouhal estimate: not settled"
            ),
        ])
    if scorecard:
        lines.extend([
            "",
            "## Design Scorecard",
            "",
            f"- Wake strength: {scorecard.wake_strength:.4f}",
            f"- Pressure drop proxy: {scorecard.pressure_drop:.4f}",
            f"- Shedding confidence: {scorecard.shedding_confidence:.0%}",
            f"- Summary: {scorecard.summary}",
        ])
    if warnings:
        lines.extend(["", "## Sanity Notes", ""])
        lines.extend(f"- **{w.title}**: {w.message}" for w in warnings)
    if scene.product.classroom_prompts:
        lines.extend(["", "## Classroom Prompts", ""])
        lines.extend(f"- {prompt}" for prompt in scene.product.classroom_prompts)
    lines.extend([
        "",
        (
            "> Generated by SStream. Treat outputs as educational/early "
            "intuition, not validated production CFD."
        ),
        "",
    ])
    Path(path).write_text("\n".join(lines), encoding="utf-8")
